#!/bin/sh
cd "${0%/*}" || exit 1
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"
runApplication -s foamMultiRun foamListTimes -rm > /dev/null 2>&1 || true
rm -rf constant/metal/polyMesh constant/polyMesh \
       log.blockMesh log.splitMeshRegions log.foamMultiRun processor*
