#!/bin/sh
cd "${0%/*}" || exit 1
. "$WM_PROJECT_DIR/bin/tools/CleanFunctions"

cleanCase
rm -rf constant/feed/polyMesh
rm -rf constant/membrane/polyMesh
rm -rf constant/permeate/polyMesh
rm -rf constant/polyMesh
rm -f  log.*
rm -f  foam.foam
rm -f  *.png
